collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2885305
  brandStrength: 0.1068808
  lightness: 0.02329749
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.9265233
typography_spectrum: 0.3157995
layout_spectrum: 0.9767025
name: Cameo
